//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColetaJaragua.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBasseColetoresEntities : DbContext
    {
        public DataBasseColetoresEntities()
            : base("name=DataBasseColetoresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tb_Banco> Tb_Banco { get; set; }
        public DbSet<Tb_Box> Tb_Box { get; set; }
        public DbSet<Tb_Cadastro_Coletores> Tb_Cadastro_Coletores { get; set; }
        public DbSet<Tb_Codigo_UM> Tb_Codigo_UM { get; set; }
        public DbSet<Tb_Empresa> Tb_Empresa { get; set; }
        public DbSet<Tb_Produto> Tb_Produto { get; set; }
        public DbSet<Tb_Tipo_Associado> Tb_Tipo_Associado { get; set; }
        public DbSet<Tb_Tipo_Civil> Tb_Tipo_Civil { get; set; }
        public DbSet<Tb_Tipo_Sexo> Tb_Tipo_Sexo { get; set; }
    }
}
