//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColetaJaragua.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Tb_Box
    {
        [Display(Name = "Código")]
        public int Codigo_Box { get; set; }
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }
        [Display(Name = "Funcionário")]
        public int Codigo_Func { get; set; }
    
        public virtual Tb_Cadastro_Coletores Tb_Cadastro_Coletores { get; set; }
    }
}
