//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColetaJaragua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Codigo_UM
    {
        public Tb_Codigo_UM()
        {
            this.Tb_Produto = new HashSet<Tb_Produto>();
        }
    
        public int Codigo_UnidadeM { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Tb_Produto> Tb_Produto { get; set; }
    }
}
