//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColetaJaragua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Empresa
    {
        public int Codigo_Empresa { get; set; }
        public string Nome_Empresa { get; set; }
        public string CNPJ { get; set; }
        public string Inscricao_Estadual { get; set; }
        public string Inscricao_Municipal { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string UF { get; set; }
        public string Telefone1 { get; set; }
        public string Telefone2 { get; set; }
        public string Contato { get; set; }
        public string EMail { get; set; }
    }
}
