//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColetaJaragua.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tb_Produto
    {
        [Display(Name = "Código Produto")]
        public int Codigo_Produto { get; set; }
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }
        [Display(Name = "Medidas")]
        public int Codigo_Medidas { get; set; }

        public virtual Tb_Codigo_UM Tb_Codigo_UM { get; set; }
    }
}
